version: '3.8'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/config:/etc/nginx
        - ./nginx/ssl/private:/etc/ssl/private
        - ./nginx/ssl/certs:/etc/ssl/certs
    networks:
        - web
networks:
  web:
    driver: bridge