version: '3.8'
services:
  nodejs:
    container_name: dicd_backend_demo
    restart: unless-stopped
    image: saikumar843/node:v1
    ports:
      - "51005:51005"
    networks:
      - node
    volumes:
      - /Documents/Expleoproject/BackendDemoProject/nodevolume:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    depends_on: 
      - mongo
      - mysql
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./dbdata:/data/db
    networks:
      - node
  mysql:
    container_name: mysql
    image: mysql/mysql-server
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - node
    volumes:
      - ./storage/docker/mysql-data:/var/lib/mysql

networks:
  node:
    driver: bridge
