version: '3'
services:
  nodejs:
    container_name: dicd_backend_demo
    restart: unless-stopped
    image: saikumar843/node:latest
    ports:
      - "51005:51005"
    networks:
      - node
    volumes:
      - /Documents/Expleoproject/BackendDemoProject/nodevolume:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on: 
      - mongo
      - mysql
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    networks:
      - node
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - node
    volumes:
      - ./config/default.json:/etc/mysql/conf.d
      - /storage/docker/mysql-data:/var/lib/mysql
  nginx:
    image: nginx:latest
    container_name: proxy
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
        - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
        - /home/ubuntu/ssl:/ssl/
